from django.conf import settings


ENABLE_COMMENT_NOTIFICATIONS = getattr(settings, 'REVIEWS_ENABLE_COMMENT_NOTIFICATIONS', True)
ENABLE_PROPOSAL_UPDATE_NOTIFICATIONS = getattr(settings, 'REVIEW_ENABLE_PROPOSAL_UPDATE_NOTIFICATIONS', True)
